# Generated by Django 2.1.1 on 2018-09-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCompanies', '0003_auto_20180928_0631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('street', 'postal_code', 'city', 'is_headquarter', 'company_owner')},
        ),
    ]
