# Generated by Django 2.1.1 on 2018-09-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCompanies', '0004_auto_20180928_0637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='office',
            unique_together=set(),
        ),
    ]
